# Generated by Django 4.2.30 on 2026-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CSVUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="csv_uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("records_imported", models.IntegerField(default=0)),
                ("records_skipped", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CrimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_place", models.CharField(db_index=True, max_length=200)),
                ("incident_weekday", models.CharField(db_index=True, max_length=20)),
                ("part_of_the_day", models.CharField(db_index=True, max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("crime_risk_score", models.FloatField(default=0.0)),
                ("murder_risk", models.FloatField(default=0.0)),
                ("rape_risk", models.FloatField(default=0.0)),
                ("kidnap_risk", models.FloatField(default=0.0)),
                ("bodyfound_risk", models.FloatField(default=0.0)),
                ("robbery_risk", models.FloatField(default=0.0)),
                ("assault_risk", models.FloatField(default=0.0)),
                ("total_crimes", models.IntegerField(default=0)),
                ("total_murders", models.IntegerField(default=0)),
                ("total_rapes", models.IntegerField(default=0)),
                ("total_kidnaps", models.IntegerField(default=0)),
                ("total_bodyfounds", models.IntegerField(default=0)),
                ("total_robberys", models.IntegerField(default=0)),
                ("total_assaults", models.IntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("Very Low", "Very Low"),
                            ("Low", "Low"),
                            ("Moderate", "Moderate"),
                            ("High", "High"),
                            ("Very High", "Very High"),
                        ],
                        db_index=True,
                        default="Very Low",
                        max_length=20,
                    ),
                ),
                ("marker_radius", models.FloatField(default=7.0)),
                ("dominant_crime", models.CharField(default="", max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at", "incident_place"],
                "indexes": [
                    models.Index(
                        fields=["risk_level"], name="crime_map_c_risk_le_4e2f40_idx"
                    ),
                    models.Index(
                        fields=["incident_place", "risk_level"],
                        name="crime_map_c_inciden_b88ceb_idx",
                    ),
                ],
                "unique_together": {
                    ("incident_place", "incident_weekday", "part_of_the_day")
                },
            },
        ),
    ]
